language: java
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
script:
  - jdk_switcher use openjdk7
  - mvn clean test jacoco:report
  - jdk_switcher use oraclejdk8
  - mvn test jacoco:report
  - jdk_switcher use oraclejdk9
  - mvn test jacoco:report coveralls:report
